apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app-deployment
  labels:
    app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: chaosmaker/booker-order-service:0.0.7
          ports:
            - containerPort: 9094
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: USER_LOGIN
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: USER_PWD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: MYSQL_DATABASE
            - name: BD_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: BD_URL
                    
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  type: ClusterIP
  selector:
    app: order-service-app
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
