apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  BD_URL: order-db-service
  MYSQL_DATABASE: booker-order
  KAFKA_URL: my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local:9092
