apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-app-deployment
  labels:
    app: account-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service-app
  template:
    metadata:
      labels:
        app: account-service-app
    spec:
      containers:
        - name: account-service-app
          image: chaosmaker/booker-account-service:0.0.8
          ports:
            - containerPort: 9097
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: account-service-secret
                  key: USER_LOGIN
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-service-secret
                  key: USER_PWD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: MYSQL_DATABASE
            - name: BD_URL
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: BD_URL
---
apiVersion: v1
kind: Service
metadata:
  name: account-service-svc
spec:
  type: LoadBalancer
  selector:
    app: account-service-app
  ports:
    - protocol: TCP
      port: 9097
      targetPort: 9097
