apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-account-deployment
  labels:
    app: mysql-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-account
  template:
    metadata:
      labels:
        app: mysql-account
    spec:
      containers:
        - name: mysql-account
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: account-service-secret
                  key: USER_LOGIN
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-service-secret
                  key: USER_PWD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-service-secret
                  key: ROOT_PWD
---
apiVersion: v1
kind: Service
metadata:
  name: account-db-service
spec:
  type: ClusterIP
  selector:
    app: mysql-account
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
